# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: getproxy

on:
  push:
    branches: [ proxy ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.5
    - name: setup env & install getproxy
      run: |
        git config --global user.name "crackmag"
        git config --global user.email "valya.spaces@gmail.com"
        pip install git+https://github.com/fate0/getproxy.git@master
    - name: run getproxy
      run: |
        getproxy --in-proxy=proxy.list --out-proxy=proxy.list.out
        mv proxy.list.out proxy.list
    - name: commit
      run: |
        rm -rf .git
        git init
        git add .
        git commit -m "`env TZ=Asia/Magadan date`"
        git remote add origin https://github.com/crackmag/proxylist.git


    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true


